apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yc1koehtp-python 
  janus-idp.io/tekton: yc1koehtp-python
  backstage.io/kubernetes-id: yc1koehtp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yc1koehtp-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml