apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yc1koehtp-python
  janus-idp.io/tekton: yc1koehtp-python
  backstage.io/kubernetes-id: yc1koehtp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yc1koehtp-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
